name: SFTP to Wordpress
on:
  push:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          username: 'makeyourmarkmyun'
          server: '144.217.123.253'
          password: ${{ secrets.MAKEYOURMARKUNCA_PASS }}
          protocol: ftps
          server-dir: '/public_html/wp-content/plugins/makeYourMark-Plugin/'
